# Generated by Django 4.1.7 on 2023-03-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
